name: Julia Package CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.9.3

          #- name: Install package dependencies
          #  run: julia --project -e 'import Pkg; Pkg.instantiate()'

    - name: Install PyTorch
      run: python3 -m pip install torch

    - name: Run tests
      run: ./runtest.sh #julia --project -e 'import Pkg; Pkg.test()'
