name: Run tests
on: 
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.0', '1', 'nightly']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.0.4
    - run: julia -e 'using Pkg; Pkg.test("shakespeare")'
