name: Julia Package CI

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.6  # Change to the desired Julia version

    - name: Install package dependencies
      run: |
        julia --project -e 'import Pkg; Pkg.instantiate()'

    - name: Run tests
      run: |
        julia --project -e 'import Pkg; Pkg.test()'
